---

- name: add ppa
  apt_repository:
    repo: 'ppa:max-c-lv/shadowsocks-libev'
  when: ansible_distribution_release == 'xenial'

- name: install shadowsocks
  apt:
    name: "{{ item }}"
    update_cache: true
  
  with_items:
    - shadowsocks-libev
  become: true
