---

- hosts: devdeck
  roles:
    - dev-base
    - dev-net
    #- dev-editor
    - {role: 'dev-gui', tags: 'user'}
    - dev-vm
    - dev-docker
    - dev-python
    - dev-oa
    - dev-awesometools
    - dev-go
    - dev-java
    - dev-js
    - dev-ml
    #- dev-snap
    #- dev-anbox
    - role: dev-ocaml
      tags:
        - dev

- hosts: ss
  roles:
    - dev-ss

- hosts: ss-do
  roles:
    - dev-ss

- hosts: ss-hk
  roles:
    - dev-ss

- hosts: ernai
  roles:
    - ernai-base
    - ernai-mlnet
