---
- name: install emacs
  when: ansible_os_family == "Archlinux"
  pacman: name=emacs
  become: true

- name: fetch emacs conf
  git: repo=https://github.com/tdsparrow/emacs-config.git
       version=unified
       dest={{ src_dir }}/emacs-config
       update=yes

- name: create emacs conf dir
  file: name={{ home_dir }}/.emacs.d state=directory

- name: enable emacs conf
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - src: '{{ src_dir }}/emacs-config/.emacs'
      dest: '{{ home_dir }}/.emacs'
    - src: '{{ src_dir }}/emacs-config/el-setup'
      dest: '{{ home_dir }}/.emacs.d/el-setup'
    - src: '{{ src_dir }}/emacs-config/local'
      dest: '{{ home_dir }}/.emacs.d/local'
    - src: '{{ src_dir }}/emacs-config/init.d'
      dest: '{{ home_dir }}/.emacs.d/init.d'
      

