- name: create xinitrc
  file:
    path: '{{ home_dir }}/.xinitrc'
    state: touch

- name: config xinitrc with fcitx
  blockinfile:
    dest: '{{ home_dir }}/.xinitrc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK fcitx"
    block: |
      fcitx
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS="@im=fcitx"
      xkbcomp $DISPLAY

- name: create xreources
  file:
    path: '{{ home_dir }}/.Xresources'
    state: touch

- name: config xinitrc for terminal
  blockinfile:
    dest: '{{ home_dir }}/.Xresources'
    marker: "! {mark} ANSIBLE MANAGED BLOCK xterm"
    block: |
      UXTerm*selectToClipboard: true
      UXTerm*faceName:Terminus:style=Regular:size=12
      UXTerm*vt100*geometry: 80x60
      UXTerm*saveLines: 16384
      UXTerm*loginShell: true
      UXTerm*charClass: 33:48,35:48,37:48,43:48,45-47:48,64:48,95:48,126:48
      UXTerm*termName: xterm-256color
      UXTerm*eightBitInput: false
      UXTerm*visualBell: true
      URxvt*visualBell: true
      URxvt*font:xft:xos4 Terminus:style=Regular:size=12

      !BLK Cursor
      #define _color0        #000d18
      #define _color8        #000d18
      !RED Tag
      #define _color1        #e89393
      #define _color9        #e89393
      !GRN SpecialKey
      #define _color2        #9ece9e
      #define _color10       #9ece9e
      !YEL Keyword
      #define _color3        #f0dfaf
      #define _color11       #f0dfaf
      !BLU Number
      #define _color4        #8cd0d3
      #define _color12       #8cd0d3
      !MAG Precondit
      #define _color5        #c0bed1
      #define _color13       #c0bed1
      !CYN Float
      #define _color6        #dfaf8f
      #define _color14       #dfaf8f
      !WHT Search
      #define _color7        #efefef
      #define _color15       #efefef
      !FMT Include, StatusLine, ErrorMsg
      #define _colorBD       #ffcfaf
      #define _colorUL       #ccdc90
      #define _colorIT       #80d4aa
      !TXT Normal, Normal, Cursor
      #define _foreground    #dcdccc
      #define _background    #1f1f1f
      #define _cursorColor   #8faf9f
      URxvt*color0         : _color0
      URxvt*color1         : _color1
      URxvt*color2         : _color2
      URxvt*color3         : _color3
      URxvt*color4         : _color4
      URxvt*color5         : _color5
      URxvt*color6         : _color6
      URxvt*color7         : _color7
      URxvt*color8         : _color8
      URxvt*color9         : _color9
      URxvt*color10        : _color10
      URxvt*color11        : _color11
      URxvt*color12        : _color12
      URxvt*color13        : _color13
      URxvt*color14        : _color14
      URxvt*color15        : _color15
      URxvt*colorBD        : _colorBD
      URxvt*colorIT        : _colorIT
      URxvt*colorUL        : _colorUL
      URxvt*foreground     : _foreground
      URxvt*background     : _background
      URxvt*cursorColor    : _cursorColor
      UXTerm*color0         : _color0
      UXTerm*color1         : _color1
      UXTerm*color2         : _color2
      UXTerm*color3         : _color3
      UXTerm*color4         : _color4
      UXTerm*color5         : _color5
      UXTerm*color6         : _color6
      UXTerm*color7         : _color7
      UXTerm*color8         : _color8
      UXTerm*color9         : _color9
      UXTerm*color10        : _color10
      UXTerm*color11        : _color11
      UXTerm*color12        : _color12
      UXTerm*color13        : _color13
      UXTerm*color14        : _color14
      UXTerm*color15        : _color15
      UXTerm*colorBD        : _colorBD
      UXTerm*colorIT        : _colorIT
      UXTerm*colorUL        : _colorUL
      UXTerm*foreground     : _foreground
      UXTerm*background     : _background
      UXTerm*cursorColor    : _cursorColor
    
- name: config xinitrc with i3
  blockinfile:
    dest: "{{ home_dir }}/.xinitrc"
    block: |
      [[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
      exec i3
