---

- name: install dev base pkgs
  pacman: name={{ item }}
  with_items:
    - base-devel
    - unzip
    - wget
    - tmux
    - strace
    - tcpdump
    - clang
    - graphviz
    - zsh
    - autojump
  become: true
